---
# tasks file for prometheus
---

- name: prometheus | create directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ dir }}/prometheus"

- name: prometheus | prometheus configuration file
  become: true
  template:
    dest: "{{ dir }}/prometheus/prometheus.yml"
    force: true
    src: prometheus-prometheus-yml.j2
    mode: 0644
  register: prometheus_configuration

- name: docker | docker-compose file
  template:
    dest: "{{ dir }}/prometheus/docker-compse.yml"
    force: true
    src: docker-docker-compose.yml.j2
    mode: 0644
  register: docker_compose_configuration

- name: prometheus | docker-python
  become: true
  apt:
    name: docker-python
    state: present

- name: prometheus | docker network
  become: true
  docker_network:
    name: "{{ prometheus_docker_network }}"
    state: present

- name: Create a volume
  docker_volume:
    name: "{{ prometheus_docker_data_volume }}"
    state: present

- name: deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: "{{ dir }}/prometheus"
    files:
    - docker-compse.yaml


