---
# defaults file for prometheus

# name of host prometheus is being installed on
host: vm301

# Docker network for prometheus components
prometheus_docker_network: prometheus

# Volume for prometheus data
prometheus_docker_data_volume: prometheus-data


user: "{{ ansible_user }}"
dir: "/home/{{ USER }}/"